spring:
  application:
    name: department-service
#  profiles:
#    active: local
#  config:
#    import: "optional:configserver:http://localhost:8888"
  profiles:
    active: heroku
  config:
    import: "optional:configserver:https://config-service-tuan.herokuapp.com"